# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki
    container_name: media
    restart: always
    ports:
      - 8080:80
    volumes:
      - /home/felipe/Desktop/Playgrounds/MediaWiki-Playground/wikiSwarm/images:/var/www/html/images
      - /home/felipe/Desktop/Playgrounds/MediaWiki-Playground/wikiSwarm/LocalSettings.php:/var/www/html/LocalSettings.php:rw
      - /home/felipe/Desktop/Playgrounds/MediaWiki-Playground/wikiSwarm/data:/var/www/data
  # command: >
    # bash -c "chown www-data:www-data /var/www/html/LocalSettings.php"
  # bash -c "chown www-data:www-data /var/www/data"
