version: "3.7"
services:
  grafana:
    image: grafana/grafana:7.1.4-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-image-renderer
      TZ: America/Argentina/Buenos_Aires
      GF_AUTH_ANONYMOUS_ORG_NAME: Match-io
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_AUTH_ANONYMOUS_ENABLED=true

    user: "0"
    volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini