version: "3.7"
services:
  database:
    image: mysql:8
    ports:
        - "5086:3306"
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_USER: admin
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: main
        MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
  login_service:
    image: login_service
    container_name: login_service
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
        - "5080:5080"
    restart: on-failure
    depends_on:
        - "database"
